---
name: Tests
"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  bats:
    name: bats
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—ï¸ Setup bats
        uses: mig4/setup-bats@v1
        with:
          # renovate: datasource=github-releases depName=bats-core/bats-core
          bats-version: 1.13.0

      - name: â¤µï¸ Check out code
        uses: actions/checkout@v6

      - name: ğŸš€ Run bats
        run: bats -r .
