---
name: Tests
"on":
  pull_request:

jobs:
  bats:
    name: bats
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—ï¸ Setup bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.10.0

      - name: â¤µï¸ Check out code
        uses: actions/checkout@v4

      - name: ğŸš€ Run bats
        run: bats -r .
